//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.ReturnBook = new HashSet<ReturnBook>();
        }
    
        public string BookID { get; set; }
        public string BookName { get; set; }
        public string Press { get; set; }
        public string Author { get; set; }
        public string IBSN { get; set; }
        public string Type { get; set; }
        public string Scraps { get; set; }
    
        public virtual BorrowBooks BorrowBooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnBook> ReturnBook { get; set; }
        public virtual Scrap Scrap { get; set; }
        public virtual Store Store { get; set; }
    }
}
