//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buy
    {
        public string BookID { get; set; }
        public string BookName { get; set; }
        public string AID { get; set; }
        public string Press { get; set; }
        public string Author { get; set; }
        public int Count { get; set; }
        public decimal Price { get; set; }
    
        public virtual Administrator Administrator { get; set; }
    }
}
