//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_borrowandback
    {
        public string id { get; set; }
        public Nullable<int> readid { get; set; }
        public string bookcode { get; set; }
        public Nullable<System.DateTime> borrowTime { get; set; }
        public Nullable<System.DateTime> ygbacktime { get; set; }
        public string sjbachtime { get; set; }
        public string borrowoper { get; set; }
        public string backoper { get; set; }
        public Nullable<bool> isback { get; set; }
    }
}
