//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_AdminPurview
    {
        public string id { get; set; }
        public string name { get; set; }
        public Nullable<bool> sysset { get; set; }
        public Nullable<bool> readset { get; set; }
        public Nullable<bool> bookset { get; set; }
        public Nullable<bool> borrowback { get; set; }
        public Nullable<bool> sysquery { get; set; }
    }
}
